import { SignalBarsPreview } from "@/registry/previews/signal-bars-preview";
import type { RegistryEntry } from "@/registry/schema";

/** Registry metadata for the copy-and-own Signal Bars readout. */
export const entry: RegistryEntry = {
  slug: "signal-bars",
  name: "Signal Bars",
  nameEs: "Barras de señal",
  category: "feedback",
  materials: ["adaptive"],
  description:
    "A stepped level readout — an ascending ladder of bars whose first N are lit — for signal strength, connection quality or password strength, with a configurable bar count, per-level wording and role=\"meter\".",
  descriptionEs:
    "Una lectura de nivel por pasos —una escalera ascendente de barras cuyas primeras N están encendidas— para intensidad de señal, calidad de conexión o fuerza de contraseña, con número de barras configurable, texto por nivel y role=\"meter\".",
  variants: [{ id: "default", label: "Default", labelEs: "Predeterminado" }],
  sizes: [
    { id: "sm", label: "Small", labelEs: "Pequeño" },
    { id: "md", label: "Medium", labelEs: "Mediano" },
    { id: "lg", label: "Large", labelEs: "Grande" },
  ],
  dependencies: {
    npm: ["class-variance-authority", "clsx", "tailwind-merge"],
    internal: ["src/lib/cn.ts"],
  },
  a11y:
    "The readout is a native role=\"meter\" — the correct role for a measurement inside a known range, rather than a progressbar, because the scale has discrete steps and no task is completing. It carries aria-valuemin of 0, aria-valuemax equal to the number of bars, aria-valuenow equal to the current level, and an aria-valuetext that spells the reading in words, for example \"Good, 3 of 4\"; role and those three aria-value attributes are omitted from the public props type so a caller can never desync the announced value from the drawn one, while aria-valuetext and aria-label stay overridable for localisation. The bars are decorative and aria-hidden as a group, and an sr-only summary sentence is always rendered, so the level reaches every reader as real text. Colour is never the sole carrier: the level is expressed by how many bars are lit, by the ascending height ladder they sit on, and by a text label that is both visible and in the accessible value, and a lit bar differs from an unlit one by treatment — solid body versus a hollow outline over a faint track — not only by hue. A level of 0 is a legitimate reading rather than an error state: every bar renders as a track, aria-valuenow is 0, and the wording falls back to emptyLabel so the meter still announces \"None, 0 of 4\". Contrast holds: the level label uses the primary text token and the name and count the muted token, each at or above 4.5:1 against a light and a dark surface, and every bar fill clears the 3:1 bar asked of an informative graphic mark. Reduced motion keeps the end state: the bars' resting state is the finished one, the stagger is a keyframe that ends there, so motion-reduce:animate-none renders the complete ladder immediately and motion-reduce:transition-none lands a level change straight on the new reading. In forced-colors mode the bounds stay drawn with a CanvasText border, a lit bar repaints to Highlight, a track becomes a GrayText outline over Canvas, ornamental shadows are dropped and all text becomes CanvasText, so the count of lit bars remains countable. There is no interactive control — it is a readout — but the root exposes a focus-visible outline with an offset, mirrored by a data-[focus=true] variant for the docs, in case a consumer makes it focusable. Nothing in render reads the clock, storage or the DOM, so the server and client markup are identical.",
  a11yEs:
    "La lectura es un role=\"meter\" nativo —el rol correcto para una medición dentro de un rango conocido, en lugar de progressbar, porque la escala tiene pasos discretos y no hay ninguna tarea completándose. Lleva aria-valuemin 0, aria-valuemax igual al número de barras, aria-valuenow igual al nivel actual y un aria-valuetext que expresa la lectura en palabras, por ejemplo \"Good, 3 of 4\"; role y esos tres atributos aria-value se omiten del tipo público de props para que quien lo use nunca pueda desincronizar el valor anunciado del dibujado, mientras que aria-valuetext y aria-label siguen siendo sustituibles para traducir. Las barras son decorativas y llevan aria-hidden como grupo, y siempre se renderiza una oración de resumen sr-only, así que el nivel llega a cualquier lector como texto real. El color nunca es el único portador: el nivel se expresa por cuántas barras están encendidas, por la escalera de alturas ascendentes en la que se apoyan y por una etiqueta de texto presente tanto visualmente como en el valor accesible, y una barra encendida se distingue de una apagada por su tratamiento —cuerpo sólido frente a contorno hueco sobre una pista tenue—, no solo por su tono. Un nivel de 0 es una lectura legítima y no un error: todas las barras se dibujan como pista, aria-valuenow vale 0 y el texto recurre a emptyLabel, de modo que el medidor sigue anunciando \"None, 0 of 4\". El contraste se mantiene: la etiqueta de nivel usa el token de texto primario y el nombre y el contador el token atenuado, cada uno con al menos 4,5:1 sobre una superficie clara y una oscura, y cada relleno de barra supera el 3:1 exigido a un gráfico informativo. El movimiento reducido conserva el estado final: el estado en reposo de las barras es el definitivo y el escalonado es un keyframe que termina ahí, así que motion-reduce:animate-none muestra la escalera completa de inmediato y motion-reduce:transition-none lleva un cambio de nivel directo a la nueva lectura. En modo de colores forzados los límites se siguen dibujando con un borde CanvasText, una barra encendida se repinta a Highlight, una pista pasa a ser un contorno GrayText sobre Canvas, se eliminan las sombras ornamentales y todo el texto pasa a CanvasText, de modo que las barras encendidas siguen siendo contables. No hay ningún control interactivo —es una lectura—, pero la raíz expone un contorno focus-visible con desplazamiento, replicado por una variante data-[focus=true] para la documentación, por si alguien la hace enfocable. Nada en el render consulta el reloj, el almacenamiento ni el DOM, así que el marcado del servidor y del cliente es idéntico.",
  sourcePath: "src/registry/ui/signal-bars.tsx",
  Preview: SignalBarsPreview,
};
