import { StatusSummaryPreview } from "@/registry/previews/status-summary-preview";
import type { RegistryEntry } from "@/registry/schema";

/** Registry entry for the self-contained Status Summary panel. */
export const entry: RegistryEntry = {
  slug: "status-summary",
  name: "Status Summary",
  nameEs: "Resumen de estado",
  category: "feedback",
  materials: ["clay", "glass", "skeuo", "adaptive"],
  description:
    "A statuspage-style panel: one headline system state announced through a live region, plus a real list of services whose state is carried by words, a glyph and a distinct silhouette.",
  descriptionEs:
    "Un panel tipo página de estado: un estado general del sistema anunciado mediante una región viva, más una lista real de servicios cuyo estado se transmite con palabras, un icono y una silueta distinta.",
  variants: [{ id: "default", label: "Default", labelEs: "Predeterminado" }],
  sizes: [
    { id: "sm", label: "Small", labelEs: "Pequeño" },
    { id: "md", label: "Medium", labelEs: "Mediano" },
    { id: "lg", label: "Large", labelEs: "Grande" },
  ],
  dependencies: {
    npm: ["class-variance-authority", "clsx", "lucide-react", "tailwind-merge"],
    internal: ["src/lib/cn.ts"],
  },
  a11y:
    "The headline is a real heading whose rank is set with headingLevel, because only the host page knows the surrounding document outline, and the panel is a region labelled by that heading. The banner around the heading is a live region: urgency=\"auto\" gives every state a polite role=\"status\" and escalates only a major outage to an assertive role=\"alert\", since interrupting a reader mid-sentence has to be reserved for the case that warrants it; both are aria-atomic so the headline and its caption are announced as one sentence, and urgency accepts polite, assertive or off when product context outranks the state. role and aria-live are omitted from the public props type so a caller cannot desync them from urgency. State is never colour alone: every service and the headline carry the full state name as real text (Operational, Degraded performance, Partial outage, Major outage, Under maintenance), a decorative aria-hidden lucide glyph, and a decorative geometric silhouette that differs per state - a filled disc, an upright triangle, a hollow ring, a diamond and a horizontal bar - so a reader who cannot separate green from amber from red gets identical information from the words and the shapes; the headline is additionally prefixed with an sr-only state label, which stateLabel localises. Services are a real ul/li list so assistive tech announces the count and can walk it item by item, and a service that links to a detail page is a real anchor whose accessible name is the service name, never a div with a click handler. While loading the list wrapper carries aria-busy=\"true\", a veil covers the stale rows and the list itself is inert, so a keyboard user cannot tab into content hidden behind that veil; disabled inerts it the same way. Last updated is a prop rather than a clock read during render, so a statically generated page and its hydrated counterpart never disagree. Under prefers-reduced-motion every animation's resting state is already its final state, so motion-reduce:animate-none renders the panel complete - same headline, same rows, same states - with no movement, the busy veil stops pulsing but stays painted, and Refreshing remains in the caption as words. Forced-colors mode keeps the panel's bounds with a CanvasText border, clears the skeuo gradient and the glass backdrop blur, repaints every glyph, silhouette and label to CanvasText, and turns the link focus ring into Highlight. Focus is only ever drawn on the service links, which is the only focusable content, using focus-visible plus a parallel data-focus hook so documentation can force the look. Text and informative glyphs measure at or above 4.5:1 on every material, including both skeuo gradient stops, glass over a light and a dark backdrop, and both adaptive colour schemes.",
  a11yEs:
    "El titular es un encabezado real cuyo nivel se define con headingLevel, porque solo la página anfitriona conoce el esquema del documento, y el panel es una región etiquetada por ese encabezado. El banner que rodea al encabezado es una región viva: urgency=\"auto\" asigna a cada estado un role=\"status\" cortés y solo eleva la interrupción mayor a un role=\"alert\" asertivo, ya que interrumpir a quien lee debe reservarse para el caso que lo justifica; ambos llevan aria-atomic para que el titular y su leyenda se anuncien como una sola frase, y urgency acepta polite, assertive u off cuando el contexto del producto pesa más que el estado. role y aria-live se excluyen del tipo público de props para que nadie pueda desincronizarlos de urgency. El estado nunca depende solo del color: cada servicio y el titular llevan el nombre completo del estado como texto real (Operational, Degraded performance, Partial outage, Major outage, Under maintenance), un icono decorativo de lucide con aria-hidden y una silueta geométrica decorativa distinta por estado - disco relleno, triángulo, anillo hueco, rombo y barra horizontal -, de modo que quien no distingue verde de ámbar o de rojo recibe la misma información en las palabras y en las formas; además el titular lleva delante una etiqueta de estado sr-only que stateLabel permite traducir. Los servicios forman una lista ul/li real para que la tecnología asistiva anuncie el número de elementos y se pueda recorrer uno a uno, y un servicio con enlace a su página de detalle es un anchor real con nombre accesible propio, nunca un div con manejador de clic. Mientras loading está activo el contenedor de la lista lleva aria-busy=\"true\", un velo cubre las filas obsoletas y la propia lista es inert, así que nadie puede tabular hacia contenido oculto tras ese velo; disabled la vuelve inerte igual. La marca de última actualización es una prop y no una lectura del reloj durante el render, por lo que una página generada estáticamente y su versión hidratada nunca discrepan. Con prefers-reduced-motion el estado de reposo de cada animación ya es su estado final, así que motion-reduce:animate-none dibuja el panel completo - mismo titular, mismas filas, mismos estados - sin movimiento, el velo de ocupado deja de pulsar pero sigue pintado y Refreshing permanece en la leyenda como palabras. El modo de colores forzados conserva los límites del panel con un borde CanvasText, elimina el degradado de skeuo y el desenfoque de glass, repinta iconos, siluetas y etiquetas a CanvasText y convierte el anillo de foco del enlace en Highlight. El foco solo se dibuja en los enlaces de servicio, que son el único contenido enfocable, mediante focus-visible más un gancho paralelo data-focus para que la documentación pueda forzar esa apariencia. El texto y los iconos informativos miden al menos 4,5:1 en cada material, incluidos ambos extremos del degradado skeuo, glass sobre fondo claro y oscuro y los dos esquemas de color de adaptive.",
  sourcePath: "src/registry/ui/status-summary.tsx",
  Preview: StatusSummaryPreview,
};
