import { TagsInputPreview } from "@/registry/previews/tags-input-preview";
import type { RegistryEntry } from "@/registry/schema";

/** Registry metadata for the copy-and-own Tags Input. */
export const entry: RegistryEntry = {
  slug: "tags-input",
  name: "Tags Input",
  nameEs: "Campo de etiquetas",
  category: "inputs",
  materials: ["clay", "glass", "skeuo", "adaptive"],
  description:
    "A field that collects a list of tokens: type and press Enter or comma to add a chip, Backspace on an empty field to delete the last, or paste a comma-separated list to add several at once. Built on a real <input> inside a material field surface, with each chip a keyboard-removable button.",
  descriptionEs:
    "Un campo que reúne una lista de tokens: escribe y pulsa Enter o coma para añadir una ficha, Backspace en el campo vacío para borrar la última, o pega una lista separada por comas para añadir varias de una vez. Construido sobre un <input> real dentro de una superficie de material, con cada ficha como un botón eliminable con el teclado.",
  variants: [{ id: "default", label: "Default", labelEs: "Por defecto" }],
  sizes: [
    { id: "sm", label: "Small", labelEs: "Pequeño" },
    { id: "md", label: "Medium", labelEs: "Mediano" },
    { id: "lg", label: "Large", labelEs: "Grande" },
  ],
  dependencies: {
    npm: ["class-variance-authority", "clsx", "tailwind-merge", "lucide-react"],
    internal: ["src/lib/cn.ts"],
  },
  a11y:
    "The text you type into is a native <input>, so caret movement, selection, IME composition and the mobile keyboard are the browser's, not a reimplementation; autofill is suppressed with autoComplete=\"off\". Enter or a comma adds the trimmed value, a comma reaching the value (mobile or paste) commits every completed token, and Backspace on an empty field removes the last chip. Each existing tag is a real <li role=\"listitem\"> inside a <ul role=\"list\">, carrying a <button aria-label=\"Remove <tag>\"> so every chip is reachable with Tab and removed with Enter or Space; removing one returns focus to the input. aria-invalid is the single source of truth for the error look — the same computed invalidity sits on the container the border keys off and on the input assistive tech reads, so the two cannot drift. aria-describedby is composed, never overwritten: it always points at a visually hidden keyboard-guidance line and, when a message is present, at the message region too. That message region is always mounted with aria-live=\"polite\" so it can announce a duplicate or over-limit rejection as text rather than by the red border alone, and a separate role=\"status\" region announces each add and remove. Focus shows a 2px :focus-visible outline scoped to the text input plus a material-specific inset well driven by focus-within (clay and skeuo press inward, glass gains contained depth, adaptive uses a restrained contact inset); remove buttons carry their own focus-visible outline. prefers-reduced-motion removes the chip's entrance travel and the well's interpolation while preserving the final state — the chip still appears. forced-colors clears the tactile shadows, material gradient and backdrop filter and restores the field bounds, chip borders and remove glyphs with CanvasText, the focus outline with Highlight and the invalid border with Mark. Contrast: typed text, placeholder and chip text all measure at or above 4.5:1 against the surface they sit on, on every material and in both colour schemes, reusing Input's measured values — placeholder / typed-text minima of clay 4.80:1 / 9.81:1, glass 5.12:1 / 7.03:1, skeuo 5.47:1 / 9.55:1, adaptive light 6.59:1 / 14.98:1 and adaptive dark 7.01:1 / 12.24:1 — and the remove glyph, being informative, inherits the same text colour rather than the softer grey decoration gets.",
  a11yEs:
    "El texto que escribes va a un <input> nativo, así que el movimiento del cursor, la selección, la composición IME y el teclado móvil son los del navegador y no una reimplementación; el autocompletado se desactiva con autoComplete=\"off\". Enter o una coma añade el valor recortado, una coma que llega al valor (móvil o pegado) confirma cada token completo, y Backspace en el campo vacío elimina la última ficha. Cada etiqueta existente es un <li role=\"listitem\"> real dentro de un <ul role=\"list\">, con un <button aria-label=\"Remove <etiqueta>\"> para que toda ficha se alcance con Tab y se elimine con Enter o Espacio; al eliminar una, el foco vuelve al input. aria-invalid es la única fuente de verdad del estado de error — la misma invalidez calculada está en el contenedor del que depende el borde y en el input que lee la tecnología de asistencia, así que no pueden desincronizarse. aria-describedby se compone, nunca se sobrescribe: siempre apunta a una línea de guía de teclado oculta visualmente y, cuando hay un mensaje, también a la región del mensaje. Esa región del mensaje está siempre montada con aria-live=\"polite\" para anunciar como texto un rechazo por duplicado o por límite en vez de depender solo del borde rojo, y una región role=\"status\" aparte anuncia cada alta y baja. El foco muestra un contorno :focus-visible de 2px acotado al input más un pozo interior propio del material impulsado por focus-within (clay y skeuo se hunden, glass gana profundidad contenida, adaptive usa un contacto sobrio); los botones de eliminar llevan su propio contorno focus-visible. prefers-reduced-motion elimina el recorrido de entrada de la ficha y la interpolación del pozo conservando el estado final — la ficha sigue apareciendo. forced-colors quita las sombras táctiles, el gradiente del material y el filtro de fondo y restaura los límites del campo, los bordes de las fichas y los glifos de eliminar con CanvasText, el contorno de foco con Highlight y el borde inválido con Mark. Contraste: el texto escrito, el placeholder y el texto de las fichas miden 4,5:1 o más contra la superficie sobre la que se apoyan, en cada material y en ambos esquemas de color, reutilizando los valores medidos de Input — mínimos placeholder / texto de clay 4,80:1 / 9,81:1, glass 5,12:1 / 7,03:1, skeuo 5,47:1 / 9,55:1, adaptive claro 6,59:1 / 14,98:1 y adaptive oscuro 7,01:1 / 12,24:1 — y el glifo de eliminar, al ser informativo, hereda el mismo color de texto en vez del gris más suave de la decoración.",
  sourcePath: "src/registry/ui/tags-input.tsx",
  Preview: TagsInputPreview,
};
